version: '3'
services:
  iris:
    image: intersystems/iris-community:2019.4.0.379.0
    container_name: qewd-iris
    ports: 
      - "52773:52773"
      - "51773:51773"
      - "8080:8080"
    volumes:
     - .:/ISC
    environment:
     - ISC_DATA_DIRECTORY=/ISC/dur
    restart: always
networks:
  default:
    ipam:
      config:
        - subnet: 172.177.0.0/16